import {createSlice} from '@reduxjs/toolkit'
const UserData={
    UserDetails:[],
    Resumes:[],
    TemplateNo:null,
    LoggedinUserData:null,
    DraftData:false,
    DraftUserid:null
}
export const UserSlice=createSlice({
    name:'UserData',
    initialState:UserData,
    reducers:{
        removeUserId:(state)=>{
            state.DraftUserid=null;
        },
        addData:(state,action)=>{
            console.log(action);
            state.UserDetails.push({
                id:action.payload.id,
                phoneNumber:action.payload.cvData.phone
            })
            if(state.DraftUserid!=null){
                console.log(state.DraftUserid)
                state.Resumes.map((item)=>{
                    if(item.CV.id===state.DraftUserid){
                        console.log(item.CV.id)
                        item.CV.name1=action.payload.cvData.name1
                        item.CV.phone1=action.payload.cvData.phone1
                        item.CV.cgpa1=action.payload.cvData.cgpa1
                        item.CV.email1=action.payload.cvData.email1
                        item.CV.graduatingYear1=action.payload.cvData.graduatingYear1
                        item.CV.intro1=action.payload.cvData.intro1
                        item.CV.project11=action.payload.cvData.project11
                        item.CV.project21=action.payload.cvData.project21
                        item.CV.school1=action.payload.cvData.school1
                        item.CV.schoolMarks1=action.payload.cvData.schoolMarks1
                        item.CV.university1=action.payload.cvData.university1
                        item.CV.website1=action.payload.cvData.website1
                        item.CV.status=action.payload.cvData.status
                        item.CV.gender=action.payload.cvData.gender
                        state.DraftUserid=null;
                    }
                })
            }
            else{
                state.Resumes.push({
                    CV:action.payload.cvData,
                    Template:action.payload.templateNo,
                    CreaterId:action.payload.createrid
                })
                state.DraftUserid=null;
            }
        },
        addTemplate:(state,action)=>{
            state.TemplateNo=action.payload;
        },
        draftData:(state,action)=>{
            console.log(action);
           state.DraftData=true;
           state.LoggedinUserData=action.payload.CV;
        },
        draftFalse:(state)=>{
         state.DraftData=false;
        },
        setDataId:(state,action)=>{
         state.DraftUserid=action.payload;
        },
        editData:(state,action)=>{
            console.log(action.payload.cvData)
            state.UserDetails.push({
                id:action.payload.id,
                phoneNumber:action.payload.cvData.phone
            })
            if(state.DraftUserid!=null){
                console.log(state.DraftUserid);
                state.Resumes.map((item)=>{
                    console.log(item.CV.id)
                    if(item.CV.id===state.DraftUserid){
                        console.log("Hai yeh pehle se")
                        item.CV.name1=action.payload.cvData.name1
                        item.CV.phone1=action.payload.cvData.phone1
                        item.CV.cgpa1=action.payload.cvData.cgpa1
                        item.CV.email1=action.payload.cvData.email1
                        item.CV.graduatingYear1=action.payload.cvData.graduatingYear1
                        item.CV.intro1=action.payload.cvData.intro1
                        item.CV.project11=action.payload.cvData.project11
                        item.CV.project21=action.payload.cvData.project21
                        item.CV.school1=action.payload.cvData.school1
                        item.CV.schoolMarks1=action.payload.cvData.schoolMarks1
                        item.CV.university1=action.payload.cvData.university1
                        item.CV.website1=action.payload.cvData.website1
                        item.CV.gender=action.payload.cvData.gender
                        // state.DraftUserid=null;
                    }
                })
            }
            else{
                state.Resumes.push({
                    CV:action.payload.cvData,
                    Template:action.payload.templateNo,
                    CreaterId:action.payload.createrid
                })
            }
            state.DraftUserid=null;
        }
    } 
})
export const{addData,addTemplate,draftData,draftFalse,editData,setDataId,removeUserId}=UserSlice.actions;
export default UserSlice.reducer;